### ISSUE TITLE
Copying commands includes "$" character

### ISSUE THREAD

**Issue by gottsman** [ehlesp/smallab-k8s-pve-guide#1]
When a user clicks the icon to copy the code to the clipboard, it includes the $ character and is not easily pasted to the command line. I can help with a PR for your guide, but I wanted to make sure you were ok first. For example.... The clipboard is filled with the text below

> $ cd /usr/share/javascript/proxmox-widget-toolkit

for the first command from the [Removing Subscriptions](https://github.com/ehlesp/smallab-k8s-pve-guide/blob/main/G006%20-%20Host%20configuration%2004%20~%20Removing%20subscription%20warning.md) page.

**Comment by ehlesp** [comment]
The `$` is there on purpose for several reasons.

- I want readers to pay attention to the commands they execute from my guides, not just blindly copy them.
- Not all the code blocks are for Linux commands, so the `$` helps tell them apart.
- Some code blocks include more than one command line, or even the output of the command.
- It's common practice in tutorials to include the `$` to indicate that what comes next is a Linux command.
- The copy button is a feature of GitHub. You may not have it in a different Markdown viewer.

I understand it's kind of a bother but, as you see, there are several good reasons to keep the `$` in place.
