### ISSUE TITLE
`net.ipv4.tcp_keepalive_time` should be 600 instead of 60

### ISSUE THREAD

**Issue by trijpstra-fourlights** [ehlesp/smallab-k8s-pve-guide#17]
## Where's the issue located

- **Guides**: G015
- **Sections**: https://github.com/ehlesp/smallab-k8s-pve-guide/blob/main/G015%20-%20Host%20optimization%2001%20~%20Adjustments%20through%20sysctl.md?plain=1#L63

## What's the problem

The `net.ipv4.tcp_keepalive_time` is off by a factor of ten. The comment says it should be set to 10 minutes, which is 600 seconds, and not 60.

**Comment by ehlesp** [comment]
You're right @trijpstra-fourlights , that value is wrong. I'll upload a fix as soon as I can. Thanks for warning about it.

**Comment by ehlesp** [comment]
I've corrected the `net.ipv4.tcp_keepalive_time` value to 600 seconds, as specified in its own explanatory comment.
