### ISSUE TITLE
GiB instead of TiB

### ISSUE THREAD

**Issue by Maathias** [ehlesp/smallab-k8s-pve-guide#4]
Pretty sure you meant TiB
https://github.com/ehlesp/smallab-k8s-pve-guide/blob/bfbbfd21108faf377471e5eae5f4169022bb06d4/G005%20-%20Host%20configuration%2003%20~%20LVM%20storage.md?plain=1#L7-L9

**Comment by ehlesp** [comment]
Right again you are. I'll fix this in my next update, together with your other reported issue.

**Comment by ehlesp** [comment]
Fixed in version 1.4.1.
