### ISSUE TITLE
Inconsistent file extension

### ISSUE THREAD

**Issue by Maathias** [ehlesp/smallab-k8s-pve-guide#5]
`.orig` vs `.bkp`

https://github.com/ehlesp/smallab-k8s-pve-guide/blob/bfbbfd21108faf377471e5eae5f4169022bb06d4/G006%20-%20Host%20configuration%2004%20~%20Removing%20subscription%20warning.md?plain=1#L18

https://github.com/ehlesp/smallab-k8s-pve-guide/blob/bfbbfd21108faf377471e5eae5f4169022bb06d4/G006%20-%20Host%20configuration%2004%20~%20Removing%20subscription%20warning.md?plain=1#L53

**Comment by ehlesp** [comment]
Fixed in version 1.4.1.
