### ISSUE TITLE
Love this.   More clarity on disk management?

### ISSUE THREAD

**Issue by chicagoandy** [ehlesp/smallab-k8s-pve-guide#7]
Thank you for pulling this together.    I am using this guide to attempt to bring K8s to my existing Proxmox setup.    This has present problems where an existing setup typically doesn't have terabytes of empty disk space.

More clarity about how to resize existing partitions to match your recommendations in https://github.com/ehlesp/smallab-k8s-pve-guide/blob/main/G005%20-%20Host%20configuration%2003%20~%20LVM%20storage.md would be awesome.

**Comment by ehlesp** [comment]
> Thank you for pulling this together.

You're welcome!

Regarding what you're asking for, I'd recommend you read the [Appendix 07](https://github.com/ehlesp/smallab-k8s-pve-guide/blob/main/G907%20-%20Appendix%2007%20~%20Resizing%20a%20root%20LVM%20volume.md) first, where I cover in more detail the resizing of a root LVM volume. Maybe that's what you're looking for.

If not, point me out what particular details do you think need "more clarity" as you say, and I'll see if a fix is required or not.

**Comment by ehlesp** [comment]
Due to lack of more information and lack of updates on this matter, I close the issue.
